services:
  asir_apache:
    container_name: asir_apache_php
    image: php:7.4-apache
    depends_on:
      - db
    networks:
      bind9_subnet:
        ipv4_address: 10.1.0.253
    volumes:
      - ./site:/var/www/html
      - ./confApache:/etc/apache2
    ports:
      - '80:80'
      - '443:433'
    dns:
      - 10.1.0.254
  bind9:
    container_name: asir_bind9
    image: internetsystemsconsortium/bind9:9.16
    networks:
      bind9_subnet:
        ipv4_address: 10.1.0.254
    volumes:
      - ./dns/conf:/etc/bind
      - ./dns/zonas:/var/lib/bind
  firefox:
    container_name: asir_firefox
    image: jlesage/firefox
    ports: 
      - '5800:5800'
    volumes:
      - ./firefox:/config:rw
    dns:
      - 10.1.0.254
    networks:
      bind9_subnet:
        ipv4_address: 10.1.0.252
  wireshark:
    image: lscr.io/linuxserver/wireshark:latest
    container_name: asir_wireshark
    cap_add:
      - NET_ADMIN
    security_opt:
      - seccomp:unconfined
    #network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./confWireshark:/config
    ports:
      - 3000:3000
    networks:
      bind9_subnet:
        ipv4_address: 10.1.0.251
  db:
    image: mysql
    container_name: asir_db_mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      bind9_subnet:
        ipv4_address: 10.1.0.250
  adminer:
    image: adminer
    container_name: asir_db_adminer
    depends_on:
      - db
    ports:
      - 8081:8080
    networks:
      bind9_subnet:
        ipv4_address: 10.1.0.249
  phpmyadmin:
    image: phpmyadmin
    container_name: asir_db_phpmyadmin
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      bind9_subnet:
        ipv4_address: 10.1.0.248
networks:
  bind9_subnet:
    external: true